version: "3"

services:
  otree1:
    build: 
      context: ./otree-server
      args: 
        OTREE_APP_FOLDER: app
    env_file:
      - config.env
      - secrets.env
    environment:
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-database1-1
    ports:
      - 9091:80
    volumes:
      - "otree-resetdb1:/opt/init"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - db-net


  database1:
    image: postgres:9.5
    env_file:
      - config.env 
      - secrets.env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "database1:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  
volumes:
  database1:
  otree-resetdb1:

networks:
  db-net:
