version: "3"

services:
  otree1:
    build: 
      context: ./otree-server
      args: 
        OTREE_APP_FOLDER: app
    env_file:
      - config.env
      - secrets.env
    environment:
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-database1-1
    ports:
      - 9091:80
    volumes:
      - "otree-resetdb1:/opt/init"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - db-net


  database1:
    image: postgres:9.5
    env_file:
      - config.env 
      - secrets.env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "database1:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  otree2:
    build: 
      context: ./otree-server
      args: 
        OTREE_APP_FOLDER: app
    env_file:
      - config.env
      - secrets.env
    environment:
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-database2-1
    ports:
      - 9092:80
    volumes:
      - "otree-resetdb2:/opt/init"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - db-net


  database2:
    image: postgres:9.5
    env_file:
      - config.env 
      - secrets.env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "database2:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:
  
  otree3:
    build: 
      context: ./otree-server
      args: 
        OTREE_APP_FOLDER: app
    env_file:
      - config.env
      - secrets.env
    environment:
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-database3-1
    ports:
      - 9093:80
    volumes:
      - "otree-resetdb3:/opt/init"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - db-net


  database3:
    image: postgres:9.5
    env_file:
      - config.env 
      - secrets.env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "database3:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:
  
volumes:
  database1:
  otree-resetdb1:
  database2:
  otree-resetdb2:
  database3:
  otree-resetdb3:

networks:
  db-net:
